misp <- data.frame(
  Nom_Prénom=c("Dr Choutri Rédha",
               "Dr Abid Mohammed",
               "Dr Achouri Mohamed",
               "Dr Bouchakour Farid",
               "Dr Lajlat omar",
               "Dr Radjai Said",
               "Dr Tiba Rédha"),
  DSP=c("IR  Médéa ",
        "DSP Ain Defla",
        "DSP Laghouat",
        "DSP Chlef",
        "DSP Médéa",
        "DSP M'SILA",
        "DSP Djelfa "),
  TEL=c("05 60 67 43 31",
        "06 65 64 90 33",
        "06 62 17 24 18",
        "07 71 54 97 34",
        "07 70 45 96 51",
        "06 71 12 20 85",
        "07 72 71 80 59"),
  Email=c("pispcoord@gmail.com",
          "abidsafa@gmail.com",
          "machouri612018@gmail.com",
          "fbouchakour@gmail.com",
          "oladjelate@gmail.com",
          "radjai123@gmail.com",
          "tibaredha@yahoo.fr")
)
